"""first migration

Revision ID: 524aec44d4be
Revises: 
Create Date: 2020-12-31 07:07:42.590975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524aec44d4be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
